name: expenses_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.6.0
  fl_chart: ^0.66.0
  intl: ^0.19.0
  flutter_colorpicker: ^1.0.3
  uuid: ^4.3.3

  firebase_core: ^2.16.0

  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  expense_repository:
    path: packages/expense_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
